server:
  port: 9092
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDb
    username: root
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  
    
  application:
    name: USER-SERVICE  
    
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
eureka:    
 client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    